version: 2

project_name: p4runtime-go-controller

before:
  hooks:
    - go mod tidy

builds:
  - id: p4ctl
    main: ./cmd/p4ctl
    binary: p4ctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: p4ctl
    ids:
      - p4ctl
    name_template: "p4ctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - NOTICE
      - README.md

checksum:
  name_template: "checksums.txt"

sboms:
  - artifacts: archive
    documents:
      - "{{ .ArtifactName }}.spdx.json"

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "--yes"
      - "${artifact}"
    artifacts: checksum
    output: true
    env:
      - COSIGN_EXPERIMENTAL=1

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: Fixes
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: Docs
      regexp: '^docs(\(.+\))?:'
      order: 2
    - title: Other
      order: 99

release:
  draft: true
  prerelease: auto
